-- Profiles table (from earlier)
create table profiles (
  id uuid primary key references auth.users not null,
  member_number text unique not null,
  full_name text,
  phone text,
  role text default 'agent',
  current_tier text default 'bronze',
  bank_account text,
  payshap_id text
);

-- Sales, deposits, payouts tables (from earlier)
create table sales (
  id bigint generated by default as identity primary key,
  agent_id uuid references profiles(id),
  amount_zar decimal(12,2),
  bottles_sold integer,
  sale_date date default current_date,
  deposit_confirmed boolean default false,
  created_at timestamp with time zone default now()
);

create table deposits (
  id bigint generated by default as identity primary key,
  reference text,
  amount_zar decimal(12,2),
  deposit_date date,
  matched_to_agent uuid,
  matched_sale_id bigint,
  created_at timestamp with time zone default now()
);

create table payouts (
  id bigint generated by default as identity primary key,
  agent_id uuid references profiles(id),
  period_ending date,
  commission_zar decimal(12,2),
  stock_allocation_zar decimal(12,2),
  payshap_status text default 'pending',
  payshap_reference text,
  created_at timestamp with time zone default now()
);

-- Enable RLS
alter table profiles enable row level security;
create policy "Users can view own profile" on profiles for select using (auth.uid() = id);
